### ISSUE TITLE
PRIORITY 1: There is no README? Or any other minimum requirements :/

### ISSUE THREAD

**Issue by iteles** [dwyl/blog#20]
This is probably (hopefully) the _only_ one of our 240+ repos without a readme.

In fact, I think it doesn't follow a single one of the minimum requirement guidelines set out in our contributing guide: https://github.com/dwyl/contributing#minimum-requirements-for-a-new-repository 😞 

Can we please rectify this situation?

<img width="836" alt="screen shot 2017-10-08 at 13 06 42" src="https://user-images.githubusercontent.com/4185328/31316659-9d614dcc-ac29-11e7-8c27-8eafd0980491.png">

**Comment by markwilliamfirth** [comment]
@iteles this one also needs a readme https://github.com/dwyl/why/issues/3

**Comment by markwilliamfirth** [comment]
Have added readme
