### ISSUE TITLE
What is Accessibility?

### ISSUE THREAD

**Issue by ghost** [dwyl/blog#3]
https://github.com/dwyl/dwyl-site/issues/83

**Comment by Cleop** [comment]
**Resources:**
- http://www.bbc.co.uk/accessibility/best_practice/what_is.shtml
- http://www.charlotteis.co.uk/incremental-accessibility/ - site no longer online
- https://github.com/iteles/styling-for-accessibility

**Comment by nelsonic** [comment]
@Cleop thanks for _proactively_ copy-pasting the relevant links here. 👍 
We aren't going to be using this repo for much longer. ⏳ 
Re-opened the _original_ issue which has more context.
But there will be a "blog" soon enough. 🔜
